# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVP
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SCLAlertView'
  pod 'NVActivityIndicatorView'
  
end
