# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.4'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SCLAlertView'
  pod 'NVActivityIndicatorView'
  pod 'EasyBinding'
  
end
